# TODO - A tester

all:
  @echo "OpenPM - Open Package Manager v0.1.0"
  @echo "Please run make install as root to install it"
  
install:
  mv client.py /usr/bin/client.py
  ln -s /usr/bin/client.py openpm
  chmod +x install.sh
  mv install.sh /usr/bin/install.sh
  ln -s /usr/bin/install.sh openpm-installer
  
